### ISSUE TITLE
Consider adding Developer Tea to the list of podcasts?

### ISSUE THREAD

**Issue by jcutrell** [FrontendMasters/front-end-handbook#12]
Hey Cody. Thank you for creating such an incredible resource for people in the front-end profession. The comprehensive nature of the handbook is impressive. Killer job.

I wanted to see if you have heard of Developer Tea, and ask you to consider adding it to your list of podcasts as a resource for developers.

[DeveloperTea.com](https://developertea.com) and [Spec's page for the show](http://spec.fm/podcasts/developer-tea) can give you an idea of what the show is about, but it's essentially a short-format show that delivers 3 times per week, and covers various topics ranging from hyper-practical to entirely soft, and everything in between.

Thanks for your consideration, but even more - thank you for your continued contribution to open source!

**Comment by 1Marc** [comment]
IMO DeveloperTea.com is way too general. It's all over the place.
