### ISSUE TITLE
Consider adding Scally CSS framework to the CSS Tools section

### ISSUE THREAD

**Issue by chris-pearce** [FrontendMasters/front-end-handbook#22]
Great job on putting together the Front-end Handbook—impressive stuff. Lots of great content in there.

I wanted to suggest my CSS framework Scally for the [CSS Tools section](http://www.frontendhandbook.com/tools/css.html). You can check it out [here](https://github.com/chris-pearce/scally)—but in a nutshell Scally is a CSS framework that provides you with a solid foundation for building reusable UIs quickly. There is a fair amount of documentation in the repo.

Cheers and keep up the good work.

**Comment by 1Marc** [comment]
Can you tell us how is it different from the options listed in the CSS Tools section? Since this is your own framework it's seeming a little too self-promotional IMO.

**Comment by chris-pearce** [comment]
Many of the frameworks listed in the CSS Tools section are opinionated, some more than others, when it comes to visual design. I believe Scally differentiates itself from these frameworks by removing those opinions and focusing on providing a strong OOCSS structure to empower users to build UI in modular and scalable way. A great comparison to Scally, one that follows similar principles is [Inuit](https://github.com/inuitcss).

Additionally Scally includes the ability to easily generate [utility](https://github.com/chris-pearce/scally/tree/master/utilities) and [object](https://github.com/chris-pearce/scally/tree/master/objects) classes at any breakpoint, [explained here](https://github.com/chris-pearce/scally/blob/master/core/mixins/_generate-at-breakpoints.scss#L6-L114).

Self promoting ones own tool isn’t a bad thing, all open source projects need advocates and I do believe Scally and other frameworks like it are an alternative readers of the Front End Handbook would benefit from considering.

**Comment by chadwithuhc** [comment]
I agree, this is not mainstream enough to be listed yet. Keep on trucking and it may be some day. My main reason is it appears to be an aggregate of other popular standards.

**Comment by chris-pearce** [comment]
Thanks for your consideration.
