### ISSUE TITLE
Consider adding "How The Internet Works" series from Khan Academy

### ISSUE THREAD

**Issue by rubenlozano** [FrontendMasters/front-end-handbook#24]
Hi Cody.

Today Khan Academy in partnership with Code.org and other companies has released a new video series explaining how Internet works. I watched them and are really cool. In my opinion, it something that I would consider to add in the Internet/Web chapter. Check it out!

https://www.khanacademy.org/partner-content/code-org/internet-works

**Comment by codylindley** [comment]
Nice! added. Thanks.

**Comment by brettimus** [comment]
@rubenlozano, thanks for opening this! Really excited to watch those videos

**Comment by rubenlozano** [comment]
You're welcome, @brettimus!
