### ISSUE TITLE
Consider alphabetizing resources

### ISSUE THREAD

**Issue by AllThingsSmitty** [FrontendMasters/front-end-handbook#38]
Looking at the many awesome lists under "Learning", should resources be alphabetized for easier at-a-glance finding? This also suggests that all resources are being given equal weight in terms of significance. I was about to PR a list that way but didn't know if that was a reason not to.

**Comment by brettimus** [comment]
+1

I also alphabetize all my CSS rules is that weird? 😬

**Comment by AllThingsSmitty** [comment]
There may be some things groupings that aren't necessarily in alpha-order but order of first, second, third, etc., like the Douglas Crockford resources, which ideally someone using this material would want to keep in that grouping's order.

**Comment by AllThingsSmitty** [comment]
Submitted PR https://github.com/FrontendMasters/front-end-handbook/pull/40.

**Comment by codylindley** [comment]
Nice work @AllThingsSmitty!
