### ISSUE TITLE
Missing "Ultimate Guide to Web Hosting" link

### ISSUE THREAD

**Issue by ylambda** [FrontendMasters/front-end-handbook#42]
[Ultimate Guide to Web Hosting](https://github.com/FrontendMasters/front-end-handbook/blame/master/learning/hosting.md#L12) is missing the href.

I'm not 100% sure which resource was intended to be here, but a little googling turned up:
- http://www.whoishostingthis.com/resources/web-hosting/
- http://webhostingmedia.net/web-hosting-guide/
- https://www.fatwallet.com/blog/ultimate-guide-to-web-hosting/

**Comment by codylindley** [comment]
Thanks. Was the first link. fixed now.
