### ISSUE TITLE
Suggestion for adding 'Jank Free' to the Browser Tools section

### ISSUE THREAD

**Issue by itsjustmath** [FrontendMasters/front-end-handbook#47]
First of all, love the handbook - great resource.

I'd like to suggest adding [Jank Free](http://jankfree.org/) to the [Performance Tools](http://www.frontendhandbook.com/tools/perf.html) section of the handbook (unless you think it fits better somewhere else). The site offers links to talks, tools, slides, articles, and videos related to diagnosing and improving issues related to: [runtime performance](https://developers.google.com/web/tools/chrome-devtools/profile/rendering-tools/analyze-runtime?hl=en), browser rendering/painting, animations, and touch/input.

> What’s stopping your web pages from getting silky smooth scrolling, buttery animation and a user experience that’s snappy and fast? Jank-free rendering performance has been shown to positively affect user engagement and experience in many large sites, but remains an area many are unaware of how to diagnose or optimize. - [Addy Osmani](http://addyosmani.com/blog/making-a-site-jank-free/)

**Comment by sdras** [comment]
+1!

**Comment by AllThingsSmitty** [comment]
👍🏼
