### ISSUE TITLE
Remove $150k Salary Reference

### ISSUE THREAD

**Issue by chadwithuhc** [FrontendMasters/front-end-handbook#51]
I believe the [$150k remote working salary reference](https://github.com/FrontendMasters/front-end-handbook/blob/a0607f9e04ab70780e1eaa027dcc9d630c081623/practice/salaries.md) is a quite exaggerated.

Before you go writing this off as a "bitterness" thing, I'd like to say my main problem with it is giving false hope for people looking to break into the field.

**Comment by 1Marc** [comment]
Hey Chad,
Not only do I personally know people making over $150k as a front-end engineer...I also did myself before starting Frontend Masters. I don't think it gives false hope -- it's a reality that you can. I'll leave it up to Cody to make the final call on this though...

**Comment by chadwithuhc** [comment]
Are they working remotely, anywhere in the world? If you use https://angel.co/salaries with Frontend Developer checked and $150k+, you'll only see jobs listed in SF and NY areas. Most not mentioning remote. It seems fair to claim $110k+.

**Comment by 1Marc** [comment]
Remotely in the US, yes. I have personally always been in the Midwest. If you are talking SF or NY the high range is actually well over $300k.
