### ISSUE TITLE
JavaScript is an untyped language

### ISSUE THREAD

**Issue by jbruni** [FrontendMasters/front-end-handbook#58]
Please check my comment here:
https://github.com/FrontendMasters/front-end-handbook/commit/01b5dccdcd91ab4fcd40b87bbf0416d4dd23f15a#commitcomment-15361978

Pardon me for the light dose of irony.

**Comment by 1Marc** [comment]
JavaScript is loosely-typed language? Might be more appropriate. Maybe @getify could make this more true somehow...

**Comment by tonykung06** [comment]
I think it is fair to say JS is not statically typed. It differs from C#, Java in that a variable can refer to difference types of values at runtime

**Comment by getify** [comment]
JavaScript [most definitely](http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-language-types) has [types](http://www.ecma-international.org/ecma-262/6.0/#sec-type). Moreover, JS has a rich system of conversions between its various types, generally called [coercion](http://www.ecma-international.org/ecma-262/6.0/#sec-type-conversion).

Saying JS is not typed is to nitpick about the word "type" as compared to other languages' definitions of that word, such as Haskell. Those arguments are pointless.

JS is not type-enforced (aka "statically typed"), in that the compiler does not check types and enforce type matches in operations. Instead, JS is loosely-typed (aka "dynamically typed"), meaning runtime conditions determine the type of a value for any given operation.

**Comment by 1Marc** [comment]
Thanks for chiming in @getify!

**Comment by jbruni** [comment]
:+1: I appreciate the discussion, and I am learning new and interesting things as it goes.
