### ISSUE TITLE
Title-casing for sections

### ISSUE THREAD

**Issue by AllThingsSmitty** [FrontendMasters/front-end-handbook#64]
Any concerns with using title-casing for section headings, e.g., "What Is a Front-End Developer?" vs. "What is a front-end developer?"?

This adds a grammatically-consistent, professional feel across the material.

If no there are no objections I've got a nice PR lined up. 👍🏼

**Comment by codylindley** [comment]
I tried keeping things consistent first and lower case was easiest to that end. But I'm down for this.

**Comment by AllThingsSmitty** [comment]
@codylindley thanks. I noticed the pattern you were following and wasn't sure. Great content either way. 👍🏼
