### ISSUE TITLE
Full-stack JS app platforms section

### ISSUE THREAD

**Issue by mg1075** [FrontendMasters/front-end-handbook#8]
4.12
https://frontendmasters.gitbooks.io/front-end-handbook/content/tools/apps.html

Possible enhancement for **Full-stack JS app platforms**.
1. Include Sails
   http://sailsjs.org/
2. Distinguish between MEAN.IO and MEAN.JS.
   The link is currently to MEAN.IO, but MEAN.JS probably also ought to be there.
   https://github.com/meanjs/mean
   http://meanjs.org/

**Comment by codylindley** [comment]
Good point about MEAN link. I'll fix that. I'm leery of adding Sails, but will continue to think on it.
